name: Publish WebNN Module

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: npmjs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1) Setup Node + cache untuk npmjs.org
      - name: Setup Node.js & npmjs registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package.json'
          registry-url: 'https://registry.npmjs.org/'
        env:
          # token untuk npmjs.org
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test -- --passWithNoTests

      # 2) Publish ke npmjs.org
      - name: Publish to npmjs.org
        run: npm publish --access public
        # setup-node sudah menulis .npmrc menggunakan NODE_AUTH_TOKEN

      # 3) Setup Node + registry untuk GitHub Packages
      - name: Setup Node.js & GitHub Packages registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@galihridhoutomo'
        env:
          # token untuk GitHub Packages
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4) Publish ke GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish --access public
