name: Publish WebNN Module

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: npmjs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test -- --passWithNoTests

      #–– Publish to npmjs.org under @galihridhoutomo/tvm ––#
      - name: Configure npmjs registry auth
        run: |
          # default registry => npmjs.org
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npmjs.org
        run: npm publish --access public

      #–– Patch package.json for GitHub Packages ––#
      - name: Patch package.json to @4211421036/tvm
        run: |
          npm pkg set name=@4211421036/tvm \
                       publishConfig.registry=https://npm.pkg.github.com/

      #–– Configure GitHub Packages auth ––#
      - name: Configure GitHub Packages auth
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc

      #–– Publish to GitHub Packages under @4211421036/tvm ––#
      - name: Publish to GitHub Packages
        run: npm publish --access public --registry=https://npm.pkg.github.com/
