name: Publish Package

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test

      # Publish to npmjs (@galihridhoutomo)
      - name: Publish to npmjs
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm config set @galihridhoutomo:registry https://registry.npmjs.org
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to GitHub Packages (@4211421036)
      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Temporarily change package name for GitHub Packages
          npm pkg set name=@4211421036/tvm
          npm config set @4211421036:registry https://npm.pkg.github.com
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          npm publish --access public
          # Revert package name change
          git checkout -- package.json
