name: Publish Package

on:
  push:
    tags: ['v*.*.*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build package
        run: npm run build

      # Publish to npmjs (@galihridhoutomo)
      - name: Publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish --access public

      # Publish to GitHub Packages (@4211421036)
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Backup original package.json
          cp package.json package.json.bak
          
          # Temporarily change name
          npm pkg set name=@4211421036/tvm
          
          # Configure GitHub registry
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
          echo "@4211421036:registry=https://npm.pkg.github.com" >> ~/.npmrc
          
          # Publish
          npm publish --access public
          
          # Restore original package.json
          mv package.json.bak package.json
