name: Publish WebNN Module

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  deployments: write
  id-token: write

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: '**/package.json'

      - name: Install dependencies (generate lock file jika perlu)
        run: |
          if [ -f package-lock.json ]; then
            echo "Lock file exists, running npm ci"
            npm ci
          else
            echo "No lock file, running npm install to generate it"
            npm install
            git config --global user.name "github-actions"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: add generated package-lock.json [skip ci]"
            git push
          fi

      - name: Build package
        run: npm run build

      - name: Run tests (skip if none)
        run: npm test -- --passWithNoTests

  publish-npmjs:
    name: Publish to npmjs.org
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment: npmjs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Publish to npmjs.org
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gh-packages:
    name: Publish to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment: npmjs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Configure GitHub Packages registry
        run: |
          echo "@4211421036:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
