name: Publish WebNN Module

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: npmjs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js & cache
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package.json'

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then npm ci; else npm install; fi

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test -- --passWithNoTests

    - name: Publish to npmjs.org
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public

    - name: Patch package.json for GitHub Packages
      run: |
        # install jq for JSON patching
        sudo apt-get update && sudo apt-get install -y jq

        # inject new name and publishConfig for GitHub Packages
        jq '.name = "@4211421036/tvm" |
            .publishConfig = { "registry": "https://npm.pkg.github.com/" }' \
           package.json > tmp.package.json
        mv tmp.package.json package.json

    - name: Configure .npmrc for GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc

    - name: Publish to GitHub Packages
      run: npm publish --access public
