name: Publish Package

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      deployments: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build package
        run: npm run build

      # Publish to npmjs (@galihridhoutomo)
      - name: Publish to npmjs
        run: |
          # Configure npmjs registry
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          
          # Publish with explicit registry
          npm publish --access public --registry=https://registry.npmjs.org

      # Publish to GitHub Packages (@4211421036)
      - name: Publish to GitHub Packages
        run: |
          # Configure GitHub Packages registry
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@galihridhoutomo:registry=https://npm.pkg.github.com" >> ~/.npmrc
          
          # Temporarily modify package.json
          cp package.json package.json.bak
          npm pkg set name=@4211421036/tvmai
          npm pkg set publishConfig.registry=https://npm.pkg.github.com
          
          # Publish with explicit registry
          npm publish --access public --registry=https://npm.pkg.github.com
          
          # Restore package.json
          mv package.json.bak package.json

      - name: Create npmjs deployment
        uses: actions/deployment@v1
        with:
          environment: 'TVM AI NPMJS'
          environment-url: ${{ env.NPM_PACKAGE_URL }}
          description: 'Published @galihridhoutomo/tvm to npmjs'
