name: Publish WebNN Module

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: npmjs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (cache only)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Generate .npmrc for both registries
        run: |
          # agar default registry = npmjs.org
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

          # agar scope @galihridhoutomo go to GitHub Packages
          echo "@galihridhoutomo:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc

      - name: Publish to npmjs.org
        run: npm publish --access public

      - name: Publish to GitHub Packages
        run: npm publish --access public --registry=https://npm.pkg.github.com/
