name: Publish WebNN Module

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: npmjs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & npmjs registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package.json'
          registry-url: 'https://registry.npmjs.org/'      # untuk npmjs
          scope: '@galihridhoutomo'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci;
          else npm install; fi

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Publish to npmjs.org
        # karena registry-url di atas sudah npmjs, langsung:
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup GitHub Packages registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@galihridhoutomo'

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
